### ISSUE TITLE
how can I get glove.6B.50d.json, why not glove.6B.50d.txt?

### ISSUE THREAD

**Issue by TPF2017** [thunlp/FewRel#1]

**Comment by gaotianyu1350** [comment]
Sorry that we hadn't uploaded `glove.6B.50d.json`. Now you can download it from [Tsinghua Cloud](https://cloud.tsinghua.edu.cn/f/b14bf0d3c9e04ead9c0a/?dl=1) or [Google Drive](https://drive.google.com/open?id=1UnncRYzDpezPkwIqhgkVW6BacIqz6EaB) and put it under `data/` folder.
