### ISSUE TITLE
run test_demo.py encounter "cuda out of memory"

### ISSUE THREAD

**Issue by HelloFranker** [thunlp/FewRel#11]
I replaced the test data set with validation data set and run "python train_demo.py gnn",on gpu,
then train gnn model finished. I run "python test_demo.py" ,with the problem "CUDA out of memory",my gpu memory is 10G, .

**Comment by HelloFranker** [comment]
Does the GNN model need so big GPU memory？Or  some wrong code in the  ”test_demo.py”

**Comment by TracyLin-lzc** [comment]
I am testing on FewRel 1.0 and my pc with a GTX1650.
Maybe you could choose a lower parameter "B"(batch size) and "Q"(num of instances for each class in the query set).
For example, for GNN I use B=2 Q=10;for metanet I use B=1 Q=5.
This is my method. Hope it works for you.
