### ISSUE TITLE
The pretrain files of FewRel 2.0

### ISSUE THREAD

**Issue by ShinTsong** [thunlp/FewRel#13]
How can I get the pretrain files(glove_mat.npy and bert-base-uncased). I cannot find any tip in README.

**Comment by gaotianyu1350** [comment]
Hi! thanks for the reminder. Now the pretrain file has been uploaded to [Tsinghua Cloud](https://cloud.tsinghua.edu.cn/f/58f57bda00eb40be8d10/?dl=1) and you can also find the instruction in the readme.
