### ISSUE TITLE
网站上数据集无法下载

### ISSUE THREAD

**Issue by macanv** [thunlp/FewRel#15]
您好，请问该数据集是免费下载的么？https://thunlp.github.io/fewrel.html 上的数据集无法下载，点击链接后跳转的是page not found.

**Comment by gaotianyu1350** [comment]
抱歉最近github更新了一下，不再原来的地址了。数据集可以在 https://github.com/thunlp/FewRel/tree/master/data  这个页面找到。其中后缀为wiki的是FewRel 1.0的数据
