### ISSUE TITLE
Bert-pair model does not work properly

### ISSUE THREAD

**Issue by None403** [thunlp/FewRel#16]
1、May I ask if you can provide the docker image that can normally run bert-pair? After a lot of attempts, including changing torch version and parameter modification, there are still many mistakes, which are all due to the environment.It feels like this is also affecting people's motivation to do more research on your data set.
2、Or can you provide me with pytorch, python and cuda versions

**Comment by gaotianyu1350** [comment]
For me pytorch >= 1.2 python >= 3.6 cuda >= 0 works fine. Can you provide some details of the error so that I can help you.

**Comment by None403** [comment]
Thank you for your reply. At your prompt, I have successfully run part of the model, but the result is quite different from that of your paper. Could you please share your parameters?

**Comment by gaotianyu1350** [comment]
I have added the reproduction command to the README.

**Comment by None403** [comment]
Sorry, I may not have made it clear. What I want to ask is the hyperparameters during model training, including the hyperparameters of model = proto (encoder = bert) & model = pair (encoder = bert)

**Comment by gaotianyu1350** [comment]
The hyperparameters are included in the command. If the command does not specifically point out the numbers, then they are the default numbers in `train_demo.py`.
