### ISSUE TITLE
mask didn't work

### ISSUE THREAD

**Issue by nttmac** [thunlp/FewRel#17]
Hi!
I found that the mask operator in sentence_encoder.py didn't work.
![image](https://user-images.githubusercontent.com/45266105/69927970-116b2900-14f5-11ea-9e25-6b8af6031fcc.png)
Maybe we should reverse their positions(mask first and then padding).
Right?

**Comment by gaotianyu1350** [comment]
Thanks for the reminder. I have fixed the bug now.
