### ISSUE TITLE
Lack of the code of transformer

### ISSUE THREAD

**Issue by lileilai** [thunlp/FewRel#18]
Hi~ i have clone the code from the repository, and the code of transformer is not found when i start to reproduce the bert-pair. Could you provided the code.

**************************
from transformers import BertTokenizer, BertModel, BertForMaskedLM, BertForSequenceClassification
*****************
Thanks~

**Comment by gaotianyu1350** [comment]
Hi, `transformers` is a python package and you can install it by using pip.
