### ISSUE TITLE
Test data missing

### ISSUE THREAD

**Issue by pzajec** [thunlp/FewRel#2]
Directory **data/** does not contain **test.json**.

**train_demo.py** throws the following exception:
```
Traceback (most recent call last):
  File "train_demo.py", line 28, in <module>
    test_data_loader = JSONFileDataLoader('./data/test.json', './data/glove.6B.50d.json', max_length=max_length)
  File "FewRel/fewshot_re_kit/data_loader.py", line 98, in __init__
    raise Exception("[ERROR] Data file doesn't exist")
Exception: [ERROR] Data file doesn't exist
```

**Comment by ProKil** [comment]
To preserve the integrity of the dataset, we do not release the test set to the public. We will help you evaluate your model on the hidden test set and post your score on the leaderboard if you wish. Please refer to [our website](http://zhuhao.me/fewrel) for details. 

You can use the validation set as test set to run our demo codes. 

Although the whole evaluation process is still under construction, if you are eager to test your model now, you can contact us via [email](mailto:zhuhao15@mails.tsinghua.edu.cn).

**Comment by pzajec** [comment]
Hi,

thank you for the explanation! I have incorrectly assumed there is other hidden test set.

Best,
Patrik
