### ISSUE TITLE
How to upload models and parameters to codelab?

### ISSUE THREAD

**Issue by xm9512** [thunlp/FewRel#20]
I have re-implemented your released code, but I encounterd a problem when I upload the models to the codelab. I have tried the upload button of the top left, but there is no response and I can find any other portal to upload them.
![微信截图_20191209175523](https://user-images.githubusercontent.com/51498682/70425983-363f3d80-1aad-11ea-9f10-f29c0d1c8441.png)

**Comment by gaotianyu1350** [comment]
You can try to use codalab terminal tool (see codalab help).
