### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by lushishuai** [thunlp/FewRel#22]
你好，请问fewrel做人类实验的时候，怎么保证不带入测试者以前学到的东西呀？我看论文中有写：Note that these labelers are not provided the name of the relations and any extra information，是在测试的时候隐藏relation，只给一个relation一个数字label么？

**Comment by gaotianyu1350** [comment]
其实数字的label也不会提供给人类，因为有这个label人类也又不上呀，只是一个数字而已。如果给了名字的话，人很容易就知道这一类是什么。不给关系的名字，就会限制人类只能通过给定的样例，对测试集中的样本进行分类。
