### ISSUE TITLE
如何理解n-way k-shot的实现

### ISSUE THREAD

**Issue by broken-dream** [thunlp/FewRel#28]
最近刚接触few-shot learning，阅读了一些文献，对n-way k-shot如何实现一直感到很疑惑。看了作者data_loader中的实现，似乎是每个episode进行一次n-way k-shot的采样。但这样做，假设采样次数足够多并且每个数据被取到的概率一样，大概会有60%的数据被sample出来，FewRel中共七万个样例，也就是说会有四万多个数据被用来训练，使用这么多数据还能叫few-shot么？还望不吝赐教。

**Comment by weidalan** [comment]
> 最近刚接触few-shot learning，阅读了一些文献，对n-way k-shot如何实现一直感到很疑惑。看了作者data_loader中的实现，似乎是每个episode进行一次n-way k-shot的采样。但这样做，假设采样次数足够多并且每个数据被取到的概率一样，大概会有60%的数据被sample出来，FewRel中共七万个样例，也就是说会有四万多个数据被用来训练，使用这么多数据还能叫few-shot么？还望不吝赐教。

你可以看一下fewrel的数据情况，训练集有64个类，验证集是16个类，两者是没有交叉的。而且在验证过程中是不回传梯度更新模型的，也就是模型在预测没有见过的类别（验证集和测试集）的时候，每次只需要比较query和support set之间关系，而support set里每个类也就是10条左右

**Comment by THUCSTHanxu13** [comment]
训练集和测试集是不交叉的，而且测试集都是新的关系，所以训练集多大都不影响。n-way k-shot指的是测试的时候每次采样n个关系，每个关系只有k个样例，然后你要学习这n个关系来进行预测，这n个关系都是训练集没有见过的。此外，测试的时候回不回传梯度不是问题，问题是你无法记录每次的数据，你训练新的关系，所以对于测试的关系，所能用的实例还是非常有限的

**Comment by pldlgb** [comment]
您好，我看代码初始的设置是n=20,k=5是吗，也就是20-way 5-shot ?
