### ISSUE TITLE
gnn model  and snail model does not work properly

### ISSUE THREAD

**Issue by weidalan** [thunlp/FewRel#29]
In the file gnn.py of the 32 row. The tensor shape mismatch when feed data to gnn model.

**Comment by weidalan** [comment]
In the file gnn.py of the 32 row. The tensor shape mismatch when feed data to gnn model.

**Comment by lushishuai** [comment]
i have the same problem with you，have you solved this？

**Comment by gaotianyu1350** [comment]
The bug has been fixed.
