### ISSUE TITLE
There is something wrong in GNN and MetaNet model

### ISSUE THREAD

**Issue by githwd2016** [thunlp/FewRel#33]
When choose gnn or metanet, the parameter in **forward** is Q that means Num of instances for each class in the queryset. However, in **framework**, it passed **Q * N_for_train + na_rate * Q** that means total_Q.

**Comment by gaotianyu1350** [comment]
The bug has been fixed.

**Comment by icoderzqliu** [comment]
> The bug has been fixed.



> [<img alt="@githwd2016" width="20" height="20" src="https://avatars.githubusercontent.com/u/20674430?s=60&amp;u=adf10900fc8304863979d57f01aa3b556ef0fa51&amp;v=4">](/githwd2016) ** [githwd2016](/githwd2016) ** commented [on 13 Mar 2020](#issue-580468917)


> The bug has been fixed.

I'm sorry, it seems that this issue isn't sloved.
In metanet:
```
def forward(self, support, query, N, K, Q):
```
In framework:
```
logits, pred = model(support, query, N_for_train, K, Q * N_for_train + na_rate * Q)
```

**Comment by icoderzqliu** [comment]
> When choose gnn or metanet, the parameter in **forward** is Q that means Num of instances for each class in the queryset. However, in **framework**, it passed **Q * N_for_train + na_rate * Q** that means total_Q.

Is this issue truly solved? Why the code is still the same?
