### ISSUE TITLE
CNN sentence embedding return the all 1 mask

### ISSUE THREAD

**Issue by hjc3613** [thunlp/FewRel#41]
when I using CNN sentence embedding, the returned mask was [1,1,1,....1,1,1], I means that all elements are 1, is there some wrong with it ?

**Comment by hjc3613** [comment]
# mask
mask = np.zeros((self.max_length), dtype=np.int32)
mask[:len(indexed_tokens)] = 1
should it use tokens instead of indexed_tokens?

**Comment by gaotianyu1350** [comment]
The mask is actually not needed here in CNN (it is reserved for PCNN).
