### ISSUE TITLE
Is there a discrepancy between paper and repository？

### ISSUE THREAD

**Issue by wjczf123** [thunlp/FewRel#46]
BERT-PAIR for Domain Adaptation (FewRel 2.0) achieves 67.41 for 5-way 1-shot in the repository and website.
But in your paper BERT-PAIR achieves 56.25 for 5-way 1-shot in your paper.
Is there a discrepancy between paper and repository？

**Comment by gaotianyu1350** [comment]
Hi, the results in the repo and the benchmark website are updated after further tuning the hyper-parameters. The method is exactly the same.

**Comment by wjczf123** [comment]
OK. Thank you a lot.
