### ISSUE TITLE
关于评测时的'test_demo.py'

### ISSUE THREAD

**Issue by Wangpeiyi9979** [thunlp/FewRel#47]
您好，请问测评时提到的test_demo.py在哪里呢，请问需要自己实现吗

**Comment by gaotianyu1350** [comment]
诶应该是文档忘记更新了，请问是哪里提到了test_demo.py?

**Comment by Wangpeiyi9979** [comment]
![Uploading image.png…]()

**Comment by Wangpeiyi9979** [comment]
https://thunlp.github.io/1/fewrel/codalab.html
Step4

**Comment by Wangpeiyi9979** [comment]
我把所有程序上传到codalab上，因为个人习惯问题，我一般先从data中预处理数据得到需要的vocab.txt，然后写入到data文件夹，最后模型构建embedder时再使用vocab.txt, 请问这个写入vocab.txt到data文件夹下的操作不被运行吗

Traceback (most recent call last):
  File "create_tool_data.py", line 37, in <module>
    with open(vocab_out_path, 'w') as f:
OSError: [Errno 30] Read-only file system: './data/vocab.txt'

这里的vocab_out_path = vocab.txt

**Comment by Wangpeiyi9979** [comment]
已经可以在网站上对dev进行评测了
