### ISSUE TITLE
在CNNSentenceEncoder中mask全为1

### ISSUE THREAD

**Issue by githwd2016** [thunlp/FewRel#48]
![image](https://user-images.githubusercontent.com/20674430/96868807-1fc18b00-14a1-11eb-9696-2441847df223.png)
经过前面的处理，indexed_tokens的长度会等于self.max_length，如果使用mask[:len(indexed_tokens)] = 1，那么mask会都是1
```
# padding
while len(indexed_tokens) < self.max_length:
       indexed_tokens.append(self.word2id['[PAD]'])
indexed_tokens = indexed_tokens[:self.max_length]
# mask
mask = np.zeros((self.max_length), dtype=np.int32)
mask[:len(indexed_tokens)] = 1
```

**Comment by gaotianyu1350** [comment]
Hi, 因为用的是CNN，所以mask在这里其实没什么用（mask是为pcnn设置的）
