### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by unknown1990** [thunlp/FewRel#50]
Unfortunately, running this command cause a segmentation fault for me:

```
python train_demo.py \
    --trainN 5 --N 5 --K 1 --Q 1 \
    --model pair --encoder bert --pair --hidden_size 768 --val_step 1000 \
    --batch_size 4  --fp16 --na_rate 5 \
```

```
Segmentation fault (core dumped)
```

Any idea how can I resolve this?

**Comment by unknown1990** [comment]
Strangely, I only get this error only on GPU machine, on CPU it works fine. @gaotianyu1350 can you please confirm if it should work on GPU as well?
Thanks!

**Comment by gaotianyu1350** [comment]
Hi,

It should also work on GPU. This seems to be a problem with your running platform. You can check the CUDA settings to see if there is anything wrong with the GPU support.

**Comment by unknown1990** [comment]
Thanks @gaotianyu1350 !. Can you please specify the version of `pytorch` and `transformers` you tested this code on.

**Comment by unknown1990** [comment]
with `torch==1.6.0` and `transformers==2.8.0` it works.

**Comment by gaotianyu1350** [comment]
Can you run other torch programs on GPU?

**Comment by unknown1990** [comment]
> Can you run other torch programs on GPU?

@gaotianyu1350 yess ; now I can also run FewRel on gpu as well.
