### ISSUE TITLE
关系名称及描述在哪？

### ISSUE THREAD

**Issue by g1kyne** [thunlp/FewRel#52]
您好，我在维基百科上查找P58这个关系时，没有找到这个关系。回看了一遍论文，发现2.3节提到所有关系的介绍和描述在附录A.2中记录，请问从哪里可以获取附录A.2  ？？  另外，在维基百科搜索部分关系时，例如，"P105": "OpenStreetMap Relation ID/关联ID"，"P14": "NTU", "P101": "ISO 3166-1 alpha-2/国家代码 (ISO 3166-1 alpha-2)"，"P1001": "DRqrykAn"，这些关系的描述很奇怪，不像我们普遍认知的常用关系，出生地，首都等等，能不能解释一下？

**Comment by gaotianyu1350** [comment]
您好，Pxx和Qxx均为Wikidata（不是Wikipedia）中的关系和实体名称，在Wikidata中就可以搜到：https://www.wikidata.org/wiki/Wikidata:Main_Page

**Comment by g1kyne** [comment]
谢谢，那请问附录A.2应该从哪里获取？

**Comment by gaotianyu1350** [comment]
https://github.com/thunlp/FewRel/blob/master/paper/fewrel1_appendix.pdf 附录2可以在这里看到

**Comment by g1kyne** [comment]
谢谢
