### ISSUE TITLE
提示Datafile不存在？

### ISSUE THREAD

**Issue by Alice828** [thunlp/FewRel#55]
训练模型时提示datafile不存在

**Comment by wutong8023** [comment]
数据集里没有提供test_wiki.json, 你可以先把valid_wiki.json复制一份，在同文件夹下命名为test_wiki.json，就可以了

**Comment by gaotianyu1350** [comment]
Hi，

请问问题是否解决？如果没有的话，还请提供更多的信息（比如具体的错误输出）

**Comment by Alice828** [comment]
问题已解决，感谢
















在 2021-06-04 14:48:29，"Tianyu Gao" ***@***.***> 写道：

Hi，

请问问题是否解决？如果没有的话，还请提供更多的信息（比如具体的错误输出）
