### ISSUE TITLE
Appendix A.2

### ISSUE THREAD

**Issue by mrvoh** [thunlp/FewRel#58]
Hi,

First of all: thanks for sharing your work!

Your paper mentions an appendix (A.2) where the used relations are described, but the appendix seems to be missing. Could you either share the full appendix or the mapping from relation keys to their name/description?

Thanks a lot!

**Comment by gaotianyu1350** [comment]
Hi, 

We provide the ID-relation name/description mapping in [this file](https://github.com/thunlp/FewRel/blob/master/data/pid2name.json) linked in README. If you want to know more about each relation, you can also use the [Wikidata official website](https://www.wikidata.org/wiki/Wikidata:Main_Page).

**Comment by mrvoh** [comment]
Amazing, thanks for the quick response!
