### ISSUE TITLE
data set problem

### ISSUE THREAD

**Issue by zhentaoCoding** [thunlp/FewRel#6]
请问数据集中实体的类别从哪可以获取到，数据中实体只有ID

**Comment by THUCSTHanxu13** [comment]
你可以通过wikidata来获取这些实体的信息，https://www.wikidata.org/wiki/Wikidata:Main_Page

**Comment by THUCSTHanxu13** [comment]
整个wikidata的dump可以从 https://www.wikidata.org/wiki/Wikidata:Database_download 上获取
