### ISSUE TITLE
some question about test

### ISSUE THREAD

**Issue by gaoyi-byte** [thunlp/FewRel#62]
比如，5-way-5shot few shot在测试阶段不是会去5*5的support data进行训练微调然后在query data上进行测试嘛，我看你的代码中在test阶段好像没有更新参数的过程？是我哪里理解错了嘛？

**Comment by gaotianyu1350** [comment]
Hi，

对于不同的few-shot模型来说，对test阶段是否更新参数有不同的设定。像ProtoNet，BERT-PAIR等基于度量的方法，通常来说是不在test阶段更新参数的，直接利用训练阶段学到的比较instance之间相似程度的能力，去在新任务上做测试；对于MAML等方法，确实需要在测试阶段更新参数。
