### ISSUE TITLE
How to obtain the NYT-25 dataset?

### ISSUE THREAD

**Issue by HeranXin** [thunlp/FewRel#63]

**Comment by HeranXin** [comment]
Hi, I found that the paper "Few-shot Relation Extraction via Bayesian Meta-learning on Relation Graphs，ICML，2020" used The dataset NYT-25, the paper described this dataset as" The raw data of NYT-25 is from The official website of Fewrel..." ，but I can't find this dataset on the given official website，so I would like to ask how to get this dataset？Thanks a lot

**Comment by THUCSTHanxu13** [comment]
Maybe you can directly contact the paper's original author.
