### ISSUE TITLE
How can I find the implementation of the top 3 models for the fewrel 2.0 domain adaptation as the benchmark website?

### ISSUE THREAD

**Issue by Alice828** [thunlp/FewRel#64]
Hello,I want to list a baseline of the fewrel 2.0 domain adaptation challenge . How can I find the  implementation or some material about the top 3 models as the benchmark website show?
![image](https://user-images.githubusercontent.com/12403381/124687615-d4082200-df07-11eb-8662-20e3c833bb71.png)

**Comment by THUCSTHanxu13** [comment]
As these users submitted their code anonymously, we also cannot trace their papers.
