### ISSUE TITLE
运行基准文件时出现PermissionError: [Errno 13] Permission denied的错误

### ISSUE THREAD

**Issue by wink-ai** [thunlp/FewRel#65]
百度说的要写文件名而不是路径，还要检查文件是否被打开等等，这些问题我检查了都没有啊，有人遇到过一样的问题没
<img width="760" alt="1628322083(1)" src="https://user-images.githubusercontent.com/51701941/128592801-2f620817-502f-436d-bc29-cc2fa229ebab.png">

**Comment by THUCSTHanxu13** [comment]
你这个应该是服务器上的文件权限不在你这个用户上吧，这个应该不是代码问题
