### ISSUE TITLE
请问framework的train()函数的parameters_to_optimize

### ISSUE THREAD

**Issue by 9876K** [thunlp/FewRel#71]
parameters_to_optimize被传到优化器optimizer中，parameters_to_optimize代表模型参数，模型假如用的bert，是不是对bert的参数进行训练了？

**Comment by THUCSTHanxu13** [comment]
这个要看具体怎么塞参数了，我们默认是优化所有参数的，但是写代码的时候可以具体选择塞哪些参数进优化器的
