### ISSUE TITLE
请问是否可以私人共享test dataset?

### ISSUE THREAD

**Issue by ZhenbinAI** [thunlp/FewRel#77]
高学长好，本人是RE方向的小萌新，然后希望能完整运行该baseline的代码，不知道test set是否方便共享，本人保证只用于代码学习并不进行传播。当然如果不便也非常理解。

**Comment by THUCSTHanxu13** [comment]
你用验证集进行测试吧，我们搞提交评测主要就是考虑不暴露测试集

**Comment by ZhenbinChan** [comment]
好的，谢谢大佬的回复。
