### ISSUE TITLE
Unable to upload prediciton file

### ISSUE THREAD

**Issue by jzhang38** [thunlp/FewRel#80]
Hi, I cannot upload my prediciton file to the Codalab website https://competitions.codalab.org/competitions/27980#participate-submit_results.  It always give me "Sorry, failed to upload file."

您好，我突然没办法在codalab  提交结果了， 每次都返回“Sorry, failed to upload file.”

Is there anyway to solve this?

Thank you!
谢谢!

**Comment by THUCSTHanxu13** [comment]
codalab有时候会出现不太稳定的情况，一段时间之后会修复的
